import type { Product } from "@/types/marketplace"

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "iPhone 15 Pro Max",
    price: 1199.99,
    originalPrice: 1299.99,
    image: "/iphone-15-pro-max.png",
    description:
      "Latest iPhone with A17 Pro chip, titanium design, and advanced camera system. Features 6.7-inch Super Retina XDR display, Action Button, and all-day battery life. Perfect for photography enthusiasts and power users.",
    rating: 4.8,
    reviews: 2847,
    category: "Electronics",
    location: "New York, NY",
    condition: "new",
    seller: "TechStore NYC",
    inStock: true,
    featured: true,
    saleStatus: undefined,
    purchaseStatus: undefined,
  },
  {
    id: 2,
    name: "Modern Sectional Sofa",
    price: 899.99,
    originalPrice: 1199.99,
    image: "/modern-gray-sectional-sofa-furniture.png",
    description:
      "Spacious 3-seater sectional sofa in contemporary gray fabric. Features deep cushions, sturdy hardwood frame, and removable covers for easy cleaning. Perfect for living rooms and family spaces.",
    rating: 4.6,
    reviews: 432,
    category: "Furniture",
    location: "Los Angeles, CA",
    condition: "new",
    seller: "HomeDesign LA",
    inStock: true,
    featured: true,
  },
  {
    id: 3,
    name: "Nike Air Jordan 1 Retro",
    price: 170.0,
    originalPrice: 200.0,
    image: "/nike-air-jordan-1-sneakers-red-black.png",
    description:
      "Iconic Air Jordan 1 in classic Chicago colorway. Premium leather construction with original design elements. Authentic and in excellent condition, perfect for collectors and sneaker enthusiasts.",
    rating: 4.9,
    reviews: 1256,
    category: "Clothing",
    location: "Chicago, IL",
    condition: "new",
    seller: "SneakerHub",
    inStock: true,
    featured: true,
  },
  {
    id: 4,
    name: "2019 Honda Civic",
    price: 18500.0,
    originalPrice: 19500.0,
    image: "/2019-honda-civic-sedan-blue-car.png",
    description:
      "Reliable 2019 Honda Civic sedan with low mileage and complete service history. Features fuel-efficient engine, CVT transmission, Honda Sensing safety suite, and excellent build quality. One owner, garage kept.",
    rating: 4.5,
    reviews: 89,
    category: "Vehicles",
    location: "Miami, FL",
    condition: "used",
    seller: "AutoDealer Miami",
    inStock: true,
    featured: true,
  },
  {
    id: 5,
    name: "MacBook Pro 16-inch M3",
    price: 2399.99,
    originalPrice: 2599.99,
    image: "/macbook-pro-16-inch-laptop-silver.png",
    description:
      "Brand new MacBook Pro 16-inch featuring the revolutionary M3 Pro chip with 12-core CPU and 18-core GPU. This powerhouse includes 18GB unified memory, 512GB SSD storage, and the stunning Liquid Retina XDR display with ProMotion technology. Perfect for professional video editing, 3D rendering, and software development. Features the advanced camera system, studio-quality three-mic array, and six-speaker sound system with Spatial Audio. Includes MagSafe 3 charging, three Thunderbolt 4 ports, HDMI port, and SDXC card slot. All-day battery life up to 22 hours video playback. Comes with 1-year AppleCare warranty and original packaging.",
    rating: 4.8,
    reviews: 1876,
    category: "Electronics",
    location: "San Francisco, CA",
    condition: "new",
    seller: "Apple Store SF",
    inStock: true,
    featured: false,
  },
  {
    id: 6,
    name: "Vintage Leather Armchair",
    price: 650.0,
    originalPrice: 850.0,
    image: "/vintage-brown-leather-armchair-furniture.png",
    description:
      "Stunning mid-century vintage leather armchair crafted from premium full-grain brown leather with beautiful patina that tells its story. Features solid hardwood frame construction with traditional mortise and tenon joinery for exceptional durability. The high-density foam cushioning provides excellent comfort while maintaining its shape over time. Hand-rubbed leather finish shows authentic character marks that add to its charm and uniqueness. Deep button tufting and rolled arms showcase classic design elements. Minor wear marks on arms and seat edges are consistent with age and add to its vintage appeal. Dimensions: 32\"W x 34\"D x 36\"H with 18\" seat height. Professional cleaning recommended.",
    rating: 4.4,
    reviews: 234,
    category: "Furniture",
    location: "Austin, TX",
    condition: "used",
    seller: "Vintage Finds",
    inStock: true,
    featured: false,
  },
  {
    id: 7,
    name: "Levi's 501 Original Jeans",
    price: 59.99,
    originalPrice: 79.99,
    image: "/levis-501-blue-denim-jeans.png",
    description:
      "Authentic Levi's 501 Original jeans in classic medium blue wash - the gold standard of denim since 1873. Made from 100% cotton denim with the iconic straight leg fit that never goes out of style. Features the original button fly, five-pocket styling, and signature arcuate stitching on back pockets. Pre-shrunk for consistent fit and constructed with reinforced stress points for maximum durability. This timeless design has been worn by generations and continues to be the most popular jean style worldwide. Perfect for everyday wear, these jeans get better with age and develop unique fading patterns. Available in waist sizes 28-40 and inseam lengths 30-36. Machine washable. New with tags.",
    rating: 4.7,
    reviews: 892,
    category: "Clothing",
    location: "Portland, OR",
    condition: "new",
    seller: "Denim Co",
    inStock: true,
    featured: false,
  },
  {
    id: 8,
    name: "2020 Tesla Model 3",
    price: 35000.0,
    originalPrice: 37000.0,
    image: "/2020-tesla-model-3-white-electric-car.png",
    description:
      "Exceptional 2020 Tesla Model 3 Long Range in pristine Pearl White Multi-Coat finish. This electric vehicle delivers an impressive 358 miles of range on a single charge with dual motor all-wheel drive for superior traction in all weather conditions. Features the latest Autopilot hardware with Full Self-Driving capability, over-the-air software updates, and the premium connectivity package. Interior boasts vegan leather seating, heated front and rear seats, premium audio system with 14 speakers, and the iconic 15-inch touchscreen display. Recent software update includes Tesla Theater, gaming, and enhanced navigation. Only 23,000 miles with complete service history and clean title. Includes mobile connector, wall connector, and all original documentation. No accidents, non-smoking owner.",
    rating: 4.9,
    reviews: 156,
    category: "Vehicles",
    location: "Seattle, WA",
    condition: "used",
    seller: "EV Motors",
    inStock: true,
    featured: false,
  },
]

export const categories = ["Electronics", "Furniture", "Clothing", "Vehicles", "Others"]

export const locations = [
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Miami, FL",
  "San Francisco, CA",
  "Austin, TX",
  "Portland, OR",
  "Seattle, WA",
]
